
training of backgammon
Traceback (most recent call last):
  File "/root/src/pgx/pgx/workspace/backgammon_training/ppo.py", line 361, in <module>
    out = train(config, rng)
  File "/root/src/pgx/pgx/workspace/backgammon_training/ppo.py", line 320, in train
    eval_R = evaluate(runner_state[0], old_train_state, network, env, rng, config["NUM_ENVS"])
  File "/root/src/pgx/pgx/workspace/backgammon_training/ppo.py", line 271, in evaluate
    state, cum_return, _ = jax.lax.while_loop(cond_fn, loop_fn, (state, cum_return, rng_key))
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 1143, in while_loop
    init_vals, init_avals, body_jaxpr, in_tree, *rest = _create_jaxpr(init_val)
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 1126, in _create_jaxpr
    body_jaxpr, body_consts, body_tree = _initial_style_jaxpr(
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/lax/control_flow/common.py", line 60, in _initial_style_jaxpr
    jaxpr, consts, out_tree = _initial_style_open_jaxpr(
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/lax/control_flow/common.py", line 54, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/interpreters/partial_eval.py", line 2150, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/interpreters/partial_eval.py", line 2172, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/root/.pyenv/versions/3.10.0/lib/python3.10/site-packages/jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/root/src/pgx/pgx/workspace/backgammon_training/ppo.py", line 269, in loop_fn
    cum_return = cum_return + jax.vmap(_get)(state.rewards, actor)
jax._src.traceback_util.UnfilteredStackTrace: NameError: name 'actor' is not defined
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/root/src/pgx/pgx/workspace/backgammon_training/ppo.py", line 361, in <module>
    out = train(config, rng)
  File "/root/src/pgx/pgx/workspace/backgammon_training/ppo.py", line 320, in train
    eval_R = evaluate(runner_state[0], old_train_state, network, env, rng, config["NUM_ENVS"])
  File "/root/src/pgx/pgx/workspace/backgammon_training/ppo.py", line 271, in evaluate
    state, cum_return, _ = jax.lax.while_loop(cond_fn, loop_fn, (state, cum_return, rng_key))
  File "/root/src/pgx/pgx/workspace/backgammon_training/ppo.py", line 269, in loop_fn
    cum_return = cum_return + jax.vmap(_get)(state.rewards, actor)
NameError: name 'actor' is not defined